# Generated by Django 3.2.21 on 2024-09-15 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_view_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='image',
            new_name='thumbnail',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='status',
            field=models.CharField(choices=[('in_review', 'In Review'), ('published', 'Published'), ('revoked', 'Revoked')], default='in_review', max_length=15),
        ),
    ]
