# Generated by Django 3.2.21 on 2024-09-15 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_userimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='view_count',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='last_read',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
