export const ENDPOINT = {
    GET_BLOG: "/blog/feeds/",
    GET_CATEGORY: "/blog/categories/",
    POST_BLOG: 'blog/blogposts/',
    AUTH_LOGIN: "auth/login/",
    AUTH_SIGNUP:"auth/sign-up",
    GET_BLOG_DETAIL: "blog/:id/",
    DELETE_BLOG: "blog/blogposts/:id/",
    EDIT_BLOG: "blog/blogposts/:id/",
    MY_BLOGS: "blog/blogposts/",
    ADMIN_GET_BLOG: "admin/blogposts/",
    ADMIN_UPDATE_STATUS: "admin/blogposts/:id/",
    ADMIN_BLOG_DETAILS: "admin/blogposts/:id/",
    ADMIN_CATEGORY_CREATE: 'admin/categories/',
}